---
name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
             echo "hello world"
             echo "times 20"
      - name: print goodbye
        run: echo "good bye!"
